### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by samkitk** [yashrajkakkad/AUtomate#1]
![Screenshot-20200110115158-608x148](https://user-images.githubusercontent.com/28357583/72130486-b05e2d00-339f-11ea-9b43-5e335b221df9.png)
> python auris.py
Traceback (most recent call last):
  File "auris.py", line 10, in <module>
    from course import Course
  File "/home/supremo/Desktop/GitHub/AUtomate/course.py", line 11
    def add_component(self, component: component):

**Comment by samkitk** [comment]
Opened course.py file and edited the code
Original Code:
`def add_component(self, component: component):`
New Code:
`def add_component(self, component):`
